[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  { name = "BuriedInCode", email = "BuriedInCode@tuta.io" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.10",
  "Typing :: Typed",
]
dependencies = [
  "fastapi >= 0.86.0",
  "jinja2 >= 3.1.2",
  "pony >= 0.7.16",
  "pydantic >= 1.10.2",
  "ratelimit >= 2.2.1",
  "requests >= 2.28.1",
  "rich >= 12.6.0",
  "tomli >= 2.0.1; python_version < \"3.11\"",
  "tomli-w >= 1.0.0",
  "uvicorn >= 0.19.0",
]
description = ""
dynamic = []
keywords = []
license = "MIT"
name = "book-manager"
readme = "README.md"
requires-python = ">= 3.10, < 3.11"
version = "0.1.0b0"

[project.optional-dependencies]
dev = [
  "pre-commit >= 2.20.0",
]

[project.scripts]

[project.urls]
Documentation = "https://github.com/Buried-In-Code/Book-Manager#readme"
Homepage = "https://pypi.org/project/Book-Manager"
Issues = "https://github.com/Buried-In-Code/Book-Manager/issues"
Source = "https://github.com/Buried-In-Code/Book-Manager"

[tool.bandit]
recursive = true
skips = ["B101"]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
default_section = "THIRDPARTY"
line_length = 100
profile = "black"
